blueprints.py
from datetime import timedelta
import flask
import pytz
from flask import Blueprint, jsonify, request, make_response
from tabulate import tabulate
from sqlalchemy.exc import SQLAlchemyError
from exts import db
from models import Post, Tag, User, Comment
from sqlalchemy import or_, text
from werkzeug.security import check_password_hash

# 创建蓝图对象
bp = Blueprint('blog', __name__)


# 主页
@bp.route('/')
@bp.route('/index/')
def index():
    page = flask.request.args.get('page', 1, type=int)
    # 实现分页，每页5篇文章
    pagination = Post.query.order_by(Post.created_time.desc()).paginate(
        page=page, per_page=5, error_out=False
    )
    posts = pagination.items
    # 实时计算评论数
    for post in posts:
        post.comment_count = post.comments.count()
        db.session.add(post)
        db.session.commit()
    return flask.render_template('index.html',
                                 posts=posts,
                                 pagination=pagination,
                                 no_posts_message="还没有任何文章！点击右上角登录后发布。")


# 关于页
@bp.route('/about/')
def about():
    return flask.render_template('about.html')


# 登录页，需要输入用户名密码所以需要添加POST方法
@bp.route('/login/', methods=['GET', 'POST'])
def login():
    # 已登录则不再重复登录
    if flask.session.get("user_id"):
        return flask.redirect(flask.url_for('blog.index'))
    # 初次进入登录页面，直接展示login.html，不对空白的输入框做验证
    if flask.request.method == 'GET':
        return flask.render_template('login.html')
    # 点击登录按钮后
    name = flask.request.form.get('name')
    user = User.query.filter(User.username == name).first()
    # 验证用户名
    if not user:
        flask.flash('不存在该用户，请重新输入！')
        return flask.render_template('login.html')
    # 验证密码
    is_pw_right = check_password_hash(user.password,
                                      flask.request.form.get('password'))
    if not is_pw_right:
        flask.flash('用户名或密码错误，请重新输入！')
        return flask.render_template('login.html')
    # 登录成功，添加会话
    flask.session['user_id'] = user.id
    return flask.redirect(flask.url_for('blog.index'))


# 注销
@bp.route('/logout/')
def logout():
    flask.session.clear()  # 清除所有的会话，包括user_id
    return flask.redirect(flask.url_for('blog.index'))


# 文章页
@bp.route('/post/<int:post_id>/')
def post(post_id):
    post_to_show = Post.query.get_or_404(post_id)
    user_timezone = 'Asia/Shanghai'  # 东8区
    # 将数据库中存储的UTC时间转换为北京时间
    local_tz = pytz.timezone(user_timezone)
    local_time = post_to_show.created_time.replace(tzinfo=pytz.utc).astimezone(local_tz)
    # 查询文章对应的评论
    comments = post_to_show.comments
    # 将所有评论的创建时间转换为北京时间
    for comment in comments:
        comment.local_time = comment.created_time.replace(tzinfo=pytz.utc).astimezone(local_tz)
        db.session.add(comment)
        db.session.commit()
    # 渲染出预计需要返回的页面
    response = make_response(
        flask.render_template('post.html',
                              post=post_to_show,
                              display_time=local_time,
                              comments=comments)
    )
    # 获取当前页面的cookie名称
    cookie_name = f'post_{post_id}_viewed'
    # 如果没有找到该cookie，识别为初次访问
    if not request.cookies.get(cookie_name):
        post_to_show.view_count += 1  # 阅读量+1
        db.session.add(post_to_show)
        db.session.commit()
        # 设置cookie，标记该浏览器已经访问过该页面，访问量不再增加
        response.set_cookie(cookie_name, 'true', max_age=timedelta(days=30))
    # 返回页面
    return response


# 文章点赞
@bp.route('/post/<int:post_id>/like/', methods=['POST'])
def like_post(post_id):
    post_to_like = Post.query.get_or_404(post_id)
    post_to_like.like_count += 1
    db.session.add(post_to_like)
    db.session.commit()
    return jsonify({'like_count': post_to_like.like_count, 'success': True})


# 评论文章
@bp.route('/post/<int:post_id>/comment/', methods=['POST'])
def create_comment(post_id):
    # 从文本框获取信息
    content = flask.request.form['content']
    commenter_name = flask.request.form['commenter_name']
    commenter_email = flask.request.form['commenter_email']
    # 创建并保存评论
    comment = Comment(content=content,
                      post_id=post_id,
                      commenter_name=commenter_name,
                      commenter_email=commenter_email)
    db.session.add(comment)
    db.session.commit()
    # 重定向至对应文章，加上#comment的页面锚点
    return flask.redirect(flask.url_for('blog.post',
                                        post_id=post_id) +
                          '#comment')


# 评论点赞
@bp.route('/comment/<int:comment_id>/like/', methods=['POST'])
def like_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.like_count += 1
    db.session.add(comment)
    db.session.commit()
    return jsonify({'like_count': comment.like_count, 'success': True})


# 评论删除
@bp.route('/comment/<int:comment_id>/delete')
def delete_comment(comment_id):
    user_id = flask.session.get("user_id")
    if not user_id:  # 未登录则不允许删除
        flask.flash('请先登录再删除评论！')
        return flask.redirect(flask.url_for('blog.login'))
    comment = Comment.query.get_or_404(comment_id)
    post_id = comment.post_id
    # 删除对应评论
    db.session.delete(comment)
    db.session.commit()
    # 重定向至对应文章，加上#comment的页面锚点
    return flask.redirect(flask.url_for('blog.post',
                                        post_id=post_id) +
                          '#comment')


# 发布文章
@bp.route('/publish/', methods=['GET', 'POST'])
def publish():
    # 未登录不允许进入发布页
    if not flask.session.get("user_id"):
        flask.flash('请先登录后再发布！')
        return flask.redirect(flask.url_for('blog.login'))
    user_id = flask.session.get("user_id")
    # 初次使用GET方法访问，直接返回发布页面
    if flask.request.method == 'GET':
        return flask.render_template('publish.html')
    # 按下发布按钮，方法变为POST
    # 获取文本框中的信息
    title = flask.request.form.get('title')
    content = flask.request.form.get('content')
    tagname = flask.request.form.get('tagname')

    if not tagname:  # 没输入标签
        tagname = '默认标签'

    # 寻找是否已经存在同名tag
    exist_tag = Tag.query.filter(Tag.tag_name == tagname).first()
    if exist_tag:  # tag已存在，加入原有的tag
        tag_id = exist_tag.id
    else:  # tag不存在，创建新的tag
        new_tag = Tag(tag_name=tagname)
        db.session.add(new_tag)
        db.session.commit()
        # 获取新创建的tag的id，用于创建新文章
        tag_id = new_tag.id
    # 创建新文章
    new_post = Post(title=title, content=content, tag_id=tag_id, user_id=user_id)
    db.session.add(new_post)
    db.session.commit()
    # 发布完成后重定向至该文章页
    return flask.redirect(flask.url_for('blog.post', post_id=new_post.id))


# 搜索页
@bp.route('/search/')
def search():
    query = flask.request.args.get('q')  # 搜索的关键字
    # 在文章标题、内容以及标签中搜索包含关键字的内容，降序排列
    posts = Post.query.join(Post.tag).filter(
        or_(Post.title.contains(query),
            Post.content.contains(query),
            Tag.tag_name.contains(query))
    ).order_by(Post.created_time.desc())

    # 搜索到的文章只用一页展示，每页展示数和搜索到的文章数相同
    pagination = posts.order_by(Post.created_time.desc()).paginate(
        page=1, per_page=posts.count(), error_out=False
    )
    posts = pagination.items
    return flask.render_template('index.html',
                                 posts=posts,
                                 pagination=pagination,
                                 no_posts_message="没有搜索到任何文章")


# 删除文章
@bp.route('/delete/<int:post_id>/')
def delete(post_id):
    user_id = flask.session.get("user_id")
    # 未登录不允许删除
    if not user_id:
        flask.flash('请先登录后再删除！')
        return flask.redirect(flask.url_for('blog.login'))
    # 搜索要删除的文章和文章对应的tag
    post_to_delete = Post.query.get_or_404(post_id)
    tag_to_check = Tag.query.get_or_404(post_to_delete.tag_id)

    # 删除文章
    db.session.delete(post_to_delete)
    # 如果没有同样标签的其他文章，就把标签也删掉
    if not Post.query.filter(Post.tag_id == tag_to_check.id).all():
        db.session.delete(tag_to_check)
    # 确认所有的数据库删除会话
    db.session.commit()
    return flask.redirect(flask.url_for('blog.index'))


# 编辑文章
@bp.route('/edit/<int:post_id>/', methods=['GET', 'POST'])
def edit(post_id):
    user_id = flask.session.get("user_id")
    # 未登录则不允许编辑
    if not user_id:
        flask.flash('请先登录后再编辑！')
        return flask.redirect(flask.url_for('blog.login'))
    # 搜索要编辑的文章，和对应的标签
    post_to_edit = Post.query.get_or_404(post_id)
    current_tag = Tag.query.get_or_404(post_to_edit.tag_id)
    # 初次进入编辑界面，预填充信息
    if flask.request.method == 'GET':
        # 把上面的文章和标签传入编辑页面
        return flask.render_template('edit.html',
                                     post=post_to_edit,
                                     tag=current_tag)
    # 按下编辑按钮，使用POST方法了
    title = flask.request.form.get('title')
    content = flask.request.form.get('content')
    tagname = flask.request.form.get('tagname')  # 新输入的tag
    if not tagname:  # 编辑页的tag一栏为空
        tagname = '默认分组'
    # 查找同名tag
    exist_tag = Tag.query.filter(Tag.tag_name == tagname).first()
    # 如果找到了同名tag
    if exist_tag:
        edited_tag_id = exist_tag.id
    else:
        # 用输入的标签名字创建新标签对象
        new_tag = Tag(tag_name=tagname)
        db.session.add(new_tag)
        db.session.commit()
        edited_tag_id = new_tag.id

    # 更新文章信息
    post_to_edit.title = title
    post_to_edit.content = content
    post_to_edit.tag_id = edited_tag_id
    db.session.add(post_to_edit)
    db.session.commit()

    # 检查旧标签是否还有关联的文章
    if not Post.query.filter(Post.tag_id == current_tag.id).all():
        db.session.delete(current_tag)  # 删除没有关联文章的旧标签
        db.session.commit()
    # 修改完毕跳转回当前文章
    return flask.redirect(flask.url_for('blog.post', post_id=post_id))


# 查看某一标签的文章
@bp.route('/tag/<int:tag_id>/')
def tag(tag_id):
    posts = Post.query.filter(Post.tag_id == tag_id).order_by(Post.created_time.desc())
    # 所有相同标签文章只用一页展示
    pagination = posts.paginate(
        page=1, per_page=posts.count(), error_out=False
    )
    posts = pagination.items
    return flask.render_template('index.html',
                                 posts=posts,

templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class='pagination'>
    <li {% if not pagination.has_prev %} class='disabled' {% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.page-1, **kwargs) }}{% else %}#{% endif %}">«</a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">…</a></li>
        {% endif %}
    {% endfor %}
    <li {% if not pagination.has_next %} class="disabled" {% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.page+1, **kwargs) }}{% else %}#{% endif %}">»</a>
    </li>
</ul>
{% endmacro %}

templates/about.html
{% extends 'base.html' %}
{% block title %}
关于
{% endblock %}
{% block main_body %}
                <div class="panel panel-default">
                    <article class="vc-blog">
                        <h1 class="vc-blog-title">关于我</h1>
                        <div class="vc-blog-content">
                            <img src="{{ url_for('static', filename='img/about_icon.jpg')}}"  alt="这是头像" width="300" height="300">
                            <p>
                                <br>班级：114514
                            </p>
                            <p>
                                学号：1919810
                            </p>
                            <div class="embed-music">
                                <iframe
                                        src="https://music.163.com/outchain/player?type=2&id=26107669&auto=0&height=66"
                                        frameborder="no"
                                        width=510
                                        height=86
                                        align=center
                                ></iframe>
                            </div>
                        </div>
                    </article>
                </div>
{% endblock %}

templates/base.html
<!DOCTYPE HTML>
<html lang="zh_CN">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='css/rewrite-bootstrap.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet" type="text/css">
    <script src="{{ url_for('static', filename='js/base.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/post.js') }}" type="text/javascript"></script>
    {% block head %}
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
    {% endblock %}
</head>
<body>
    <header class="vc-header">
        <nav class="navbar navbar-default" data-spy="affix" data-offset-top="80">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{{ url_for('blog.index') }}">
                        <h4>flaskblog</h4>
                    </a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('blog.index') }}">首页</a></li>
                    <li><a href="{{ url_for('blog.statistics') }}">统计</a></li>
                    {% if user %}
                        <li><a href="{{ url_for('blog.publish') }}">发表</a></li>
                        <li><a href="{{ url_for('blog.logout') }}">注销（当前{{ user.username }}已登录）</a></li>
                    {% else %}
                        <li><a href="{{ url_for('blog.login') }}">登录</a></li>
                    {% endif %}
                    <li>
                        <form role="search" action="{{ url_for('blog.search') }}" class="navbar-form navbar-left">
                            <div class="form-group">
                                <input type="text" name="q" class="form-control" placeholder="回车搜索...">
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container vc-container">
        <div class="row">
            <div class="col-12 col-md-9">
                {% block main_body %}{% endblock %}
            </div>
            <div class="col-12 col-md-3">
                <div class="panel panel-default">
                    <h4 class="vc-widget-title">项目说明</h4>
                    <div class="panel-body">
                        <p>
                            2024年数据库大作业，使用flask框架开发的博客demo。账号与密码请见本人提交的报告。
                        </p>
                    </div>
                </div>
                <div class="panel panel-default">
                    <h4 class="vc-widget-title">功能说明</h4>
                    <div class="panel-body">
                        <ul class="function-info">
                            <li>登录用户可撰写新文章</li>
                            <li>登录用户可删除已有文章</li>
                            <li>关键字检索（标签、正文、标题）</li>
                            <li>按照标签分类展示文章</li>
                            <li>删除文章不会造成标签冗余</li>
                            <li>任意游客可评论文章</li>
                            <li>登录用户可删除文章评论</li>
                            <li>提供链接可跳转的统计数据页面</li>
                            <li>可以点赞文章和评论并实时更新</li>
                            <li>可以显示文章阅读量</li>
                            <li>登录用户可以使用sql原语查询</li>
                            <li>游客无法进行登录用户专属操作</li>
                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <h4 class="vc-widget-title">相关链接</h4>
                    <div class="panel-body">
                        <div style="display: flex; flex-direction: column;">
                            <a href="https://www.dlut.edu.cn/" class="vc-a">大连理工大学</a>
                            <a href="https://cs.dlut.edu.cn/" class="vc-a">计算机科学与技术学院</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="vc-footer">
        <div class="vc-footer-copyright">
            <div> flaskblog Copyright © 2024
            </div>
            Powered by <a class="vc-a" href="{{ url_for('blog.about') }}">yuuhicho_1919810</a>
        </div>
    </footer>
</body>
</html>

templates/edit.html
{% extends 'base.html' %}
{% block title %}
编辑
{% endblock %}
{% block main_body %}
    <div class="panel panel-default">
        <div class="well well-sm text-center">
            编辑文章
        </div>
        <article class="vc-blog">
            <form action="" method="post">
                <div class="">
                    <div class="form-group">
                        <input type="text" name="title"  value='{{ post.title |safe }}' class="form-control">
                    </div>
                    <div class="form-group">
                        <textarea name="content"  id="" class="form-control" rows="50">{{ post.content |safe }}</textarea>
                    </div>
                    <div class="form-group">
                        <input type="text" name="tagname" value="{{ tag.tag_name |safe }}" placeholder="请在此输入要更改的标签，留空则为默认分组" class="form-control">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-block">立即发布</button>
                    </div>
                </div>
            </form>
        </article>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
文章列表
{% endblock %}

{% block main_body %}
<div class="main_body">
    {% if posts %}
        {% for post in posts %}
        <div class="thumbnail">
            <div class="caption">
                <h1 class="vc-page-title">
                    <a href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
                </h1>
                <p class="hidden-xs">
                    {{ post.content[:30]|striptags }}……
                    <a class="vc-more-link" href="{{ url_for('blog.post', post_id=post.id) }}" role="button">点击阅读全文 &raquo;</a>
                </p>
                <p class="post-info">
                     👁{{ post.view_count }} &bull; ❤{{ post.like_count }} &bull; 💬{{ post.comment_count }}
                </p>
                <p class="clearfix">
                    <span class="vc-tags">
                        <a href="{{ url_for('blog.tag', tag_id=post.tag_id) }}">标签：{{ post.tag.tag_name }}</a>
                    </span>
                </p>
            </div>
        </div>
        {% endfor %}
    {% else %}
{#       如果没有帖子，就显示 no_posts_message#}
        <div class="alert alert-info">{{ no_posts_message }}</div>
    {% endif %}
    <nav>
        {% import "_macros.html" as macros %}
        <div class="pagination">
            {{ macros.pagination_widget(pagination, 'blog.index') }}
        </div>
    </nav>
</div>
{% endblock %}
``

templates/login.html
{% extends 'base.html' %}

{% block title %}
登录
{% endblock %}

{% block main_body %}
<div class="panel panel-default">
    <article class="vc-blog">
        <h3 align="center">登录</h3>
        <form action="" method="post">
            <div class="form-container">
                <div class="form-group">
                    <input type="text" name="name" placeholder="姓名" class="form-control">
                </div>
                <div class="form-group">
                    <input type="password" name="password" placeholder="密码" class="form-control">
                </div>
                <div class="form-group">
                    <button class="btn btn-primary btn-block">立即登录</button>
                </div>
            </div>
        </form>
        {% for message in get_flashed_messages() %}
        <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
    </article>
</div>
{% endblock %}

templates/post.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block main_body %}
<div class="panel panel-default">
    <post class="vc-blog">
        <h1 class="vc-blog-title">{{ post.title }}</h1>
        <p class="vc-author-info">
            <time>{{ display_time.strftime('%Y-%m-%d %H:%M:%S') }}</time> &bull; <a href="{{ url_for('blog.about') }}">{{ post.user.username }}</a> &bull; 👁{{ post.view_count }} &bull;
            <a class="like-info"> <button class="like-button" onclick="like_post({{ post.id }})">❤</button><span id="like_count_{{ post.id }}">{{ post.like_count }}</span>
                </a>
        </p>
        <div class="vc-blog-content">
            {{ post.content.replace('\n', '<br>')|safe }}
        </div>
        <span class="vc-tags">
            <a href="{{ url_for('blog.tag', tag_id=post.tag_id) }}">标签：{{ post.tag.tag_name }}</a>

            {% if user %}
            <a href="{{ url_for('blog.edit', post_id=post.id) }}">编辑</a>
            <a href="{{ url_for('blog.delete', post_id=post.id) }}" onclick="return confirm('确认要删除吗？');">删除</a>
            {% endif %}
        </span>
        <div class="vc-comments" id="comment">
            <h2>评论：</h2>
                {% for comment in comments %}
                    <div class="vc-comment" >
                        <strong>{{ comment.commenter_name }}({{ comment.commenter_email }}): </strong><br>
                        <br>{{ comment.content }}<br>

                        <br><time>发表于{{ comment.local_time.strftime('%Y-%m-%d %H:%M:%S') }}  &bull;</time>
                            <a class="like-info" ><button class="like-button" onclick="like_comment({{ comment.id }})">❤</button><span id="like_count_{{ comment.id }}">{{ comment.like_count }}</span>
                    </a>
                        <span class="vc-tags">
                            {% if user %}
                            <a href="{{ url_for('blog.delete_comment', comment_id=comment.id) }}" onclick="return confirm('确认要删除这条评论吗？');">删除</a>
                            {% endif %}
                        </span>
                    </div>
                {% else %}
                <li>还没有任何评论</li>
                {% endfor %}
        </div>
        <div class="vc-add-comment">
            <h3>添加新评论：</h3>
            <form action="{{ url_for('blog.create_comment', post_id=post.id) }}" method="post">
                <input type="text" placeholder="请输入昵称" name="commenter_name" required><br>
                <input type="email" placeholder="请输入邮箱" name="commenter_email" required><br>
                <input type="text" placeholder="请输入评论" name="content" required>
                <button type="submit">发送评论</button>
            </form>
        </div>
        <div class="vc-copyright">
            转载请注明：文章转载自：flaskblog（<a href="https://flaskblog.example/">https://flaskblog.example/a>）
        </div>
    </post>
</div>
{% endblock %}

templates/publish.html
{% extends 'base.html' %}
{% block title %}
撰写
{% endblock %}

{% block main_body %}
 <!-- CODE START -->
    <div class="panel panel-default">
        <div class="well well-sm text-center">
            撰写文章
        </div>
        <article class="vc-blog">
            <form method="post">
                <div class="form-group">
                    <input type="text" name="title" placeholder="请输入标题" class="form-control">
                </div>
                <div class="form-group">
                    <textarea name="content" placeholder="请输入内容" id="" class="form-control" rows="50"></textarea>
                </div>
                <div class="form-group">
                    <input type="text" name="tagname" placeholder="请输入标签，留空则统一设置为默认标签" class="form-control">
                </div>
                <div class="form-group">
                    <button class="btn btn-primary btn-block">立即发布</button>
                </div>
            </form>
        </article>
    </div>
{% endblock %}

templates/sql_search.html
{% extends 'base.html' %}
{% block title %}
SQL_查询结果
{% endblock %}
{% block main_body %}
    <div class="panel panel-default">
            <article class="vc-blog">
                <h1 class="vc-blog-title">查询结果</h1>
                <div class="vc-blog-content">
                    <div class="sql-result">
                    <br>{{ results }}
                    </div>
            </div>
            </article>
    </div>
{% endblock %}

templates/statistics.html
{% extends 'base.html' %}
{% block title %}
统计
{% endblock %}
{% block main_body %}
                <div class="panel panel-default">
                    <article class="vc-blog">
                        <h1 class="vc-blog-title">数据统计</h1>
                        <div class="vc-blog-content">
                        <h4>标签统计</h4>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>标签</th>
                                    <th>文章</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for tag_id, tag_name, post_count in tag_post_counts %}
                                <tr>
                                    <td><a href="{{ url_for('blog.tag', tag_id=tag_id) }}">{{ tag_name }}</a></td>
                                    <td>{{ post_count }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        <h4>访问统计</h4>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>文章</th>
                                    <th>访问数</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for post_id, post_title, view_count in post_view_counts %}
                                <tr>
                                    <td><a href="{{ url_for('blog.post', post_id=post_id) }}">{{ post_title }}</a></td>
                                    <td>{{ view_count }}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                        </table>

                        <h4>文章点赞统计</h4>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>文章</th>
                                    <th>点赞数</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for post_id, post_title, like_count in post_like_counts %}
                                <tr>
                                    <td><a href="{{ url_for('blog.post', post_id=post_id) }}">{{ post_title }}</a></td>
                                    <td>{{ like_count }}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                        </table>

                        <h4>评论统计</h4>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>文章</th>
                                    <th>评论数</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for post_id, post_title, comment_count in post_comment_counts %}
                                <tr>
                                    <td><a href="{{ url_for('blog.post', post_id=post_id) }}#comment">{{ post_title }}</a></td>
                                    <td>{{ comment_count }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        <h4>评论点赞统计</h4>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>所在文章</th>
                                    <th>评论者</th>
                                    <th>评论点赞数</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for post_id, commenter_name, comment_like_count, post_title in comment_like_counts %}
                                <tr>
                                    <td><a href="{{ url_for('blog.post', post_id=post_id) }}">{{ post_title }}</a></td>
                                    <td><a href="{{ url_for('blog.post', post_id=post_id) }}#comment">{{ commenter_name }}</a></td>
                                    <td>{{ comment_like_count }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
{#                        {% if user %}#}
                            <h4>SQL语句查询</h4>
                            <div class="panel-body">
                                <p>
                                    为保证安全，只提供select语句的功能，其他语句无效。<br>
                                    表结构如下：<br><br>
                                    users: id(主码), username, password<br>
                                    tags: id(主码), tag_name<br>
                                    posts: id(主码), title, content, created_time, view_count, like_count, comment_count, tag_id(外键), user_id(外键)<br>
                                    comments: id(主码), content, created_time, local_time, like_count, commenter_name, commenter_email, post_id(外键)<br>
                                </p>
                            </div>
                            <form role="search"  action="{{ url_for('blog.sql_search') }}">
                                    <div class="form-group">
                                        <input type="text" name="sql_query" class="form-control" placeholder="回车查询…">
                                    </div>
                            </form>
{#                        {% endif %}#}
{#                    </div>#}
                    </div>
                    </article>
                </div>
{% endblock %}